(SETQ UP 0)
(SETQ RIGHT 1)
(SETQ DOWN 2)
(SETQ LEFT 3)

(SETQ ON-LEFT-HALF (LAMBDA (WORLD)
  (LESSP (CAR (CADR (CADR WORLD))) 13)

(SETQ INITIAL-STATE 0)
(SETQ STEP-FUNCTION (LAMBDA (AI-STATE WORLD-STATE)
  (COND ((ON-LEFT-HALF WORLD-STATE) (CONS 0 RIGHT))
        (T (CONS 0 LEFT))))))

(SETQ MAIN (LAMBDA (WORLD UNKNOWN)
  (CONS INITIAL-STATE STEP-FUNCTION)))
